// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/google-sheets-import/values-smoke': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google-sheets-import/values-smoke.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/@nuxt+nitro-server@4.3.1_better-sqlite3@12.6.2_db0@0.3.4_better-sqlite3@12.6.2__ioredis_91cd454e5d57b3f106a75c9b3839613d/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/google-sheets-import/sheets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/sheets.get').default>>>>
    }
    '/api/google-sheets-import/values': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/values.post').default>>>>
    }
    '/api/google-sheets-import/collection-type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/collection-type.get').default>>>>
    }
    '/api/google-sheets-import/write': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/write.post').default>>>>
    }
  }
}
export {}