// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+nitro-server@4.3.1_better-sqlite3@12.6.2_db0@0.3.4_better-sqlite3@12.6.2__ioredis_c8342ab9eeca6a666b8c88339ceb526f/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/google-sheets-import/sheets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/sheets.get').default>>>>
    }
    '/api/google-sheets-import/values': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/values.post').default>>>>
    }
    '/api/google-sheets-import/collection-type': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/collection-type.get').default>>>>
    }
    '/api/google-sheets-import/schema-columns': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/schema-columns.get').default>>>>
    }
    '/api/google-sheets-import/write': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../src/runtime/server/api/write.post').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_@types+node@25.3.3_jiti@2.6.1_lightningcss@1_8495397827da8820aea2eabb0a7c41d0/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_content/exampleSchema/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/exampleSchema/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_magicast@0.5.2/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}